### ISSUE TITLE
Question regarding perfduration

### ISSUE THREAD

**Issue by derselbst** [arookas/MIDItoBMS#1]
Hi, I'm trying to write a bms to midi converter for LuigisMansion. Have you figured out how exactly perfduration works? From my understanding e.g. in case of a pitch event:

0x96 0x01 XX 0x0A

the pitch would be pulled from its current value towards XX in a linear way until it finally reaches XX after 10 pulses/ticks. is this correct?

**Comment by arookas** [comment]
Yes, that would be correct.

**Comment by derselbst** [comment]
thanks!
